stages:
  prepare_dataloader:
    cmd: python prepare_dataloader.py
    deps:
    - prepare_dataloader.py
    params:
    - dataset
    outs:
    - ${dataset.train_loader_path}
    - ${dataset.val_loader_path}
    - ${dataset.test_loader_path}

  train:
    cmd: python train.py
    deps:
    - ${dataset.train_loader_path}
    - ${dataset.val_loader_path}
    - train.py
    params:
    - dataset
    - train
    outs:
    - dvclive/plots
    - logs/checkpoints


metrics:
- dvclive/metrics.json


plots:
- Train Loss:
    x:
      dvclive/plots/metrics/train/loss.tsv: step
    y:
      dvclive/plots/metrics/train/loss.tsv: loss
- Validation Loss:
    x:
      dvclive/plots/metrics/val/loss.tsv: step
    y:
      dvclive/plots/metrics/val/loss.tsv: loss
