dataset:
  root_dir: /home/aldo/opt/dataset/Anti-UAV-RGBT
  train_loader_path: data/train_dataloader.pickle
  val_loader_path: data/val_dataloader.pickle
  test_loader_path: data/test_dataloader.pickle
  batch_size: 4
  remote: false
  image_size:
  - 640
  - 640
  workers: 32
  mosaic: false
  format: yolo
train:
  seed: 211
  trainer:
    epochs: 2
    input_size:
    - 3
    - 640
    - 640
    profiler: null
    grad_batches: 2
    train_batches: 1.0
    val_batches: 1.0
    val_check_interval: 1.0
    accelerator: gpu
    devices: 1
    precision: 16
    grad_clip_val: null
  checkpoint:
    dir: logs/checkpoints
    monitor: val_loss
    mode: min
model:
  name: baseline
  hparams:
    anchors:
    - - - 199
        - 73
      - - 315
        - 92
      - - 268
        - 182
    - - - 91
        - 54
      - - 120
        - 75
      - - 157
        - 60
    - - - 29
        - 23
      - - 48
        - 30
      - - 67
        - 38
    head_scales:
    - 32
    - 16
    - 8
    lr: 0.0001
    lr_scheduler: false
    loss_balancing:
      obj_scales_w:
      - 0.5
      - 1.0
      - 2.0
      bbox_w: 4.0
      objectness_w: 1.0
      no_obj_w: 4.0
    bbox_loss_fn: ciou
    optim:
      name: SGD
      momentum: 0.7
    layer_config:
    - - 32
      - 3
      - 1
    - - 64
      - 3
      - 2
    - - B
      - 1
    - - 128
      - 3
      - 2
    - - B
      - 2
    - - 256
      - 3
      - 2
    - - B
      - 8
    - - 512
      - 3
      - 2
    - - B
      - 8
    - - 1024
      - 3
      - 2
    - - B
      - 4
    - - 512
      - 1
      - 1
    - - 1024
      - 3
      - 1
    - - S
    - - 256
      - 1
      - 1
    - - U
    - - 256
      - 1
      - 1
    - - 512
      - 3
      - 1
    - - S
    - - 128
      - 1
      - 1
    - - U
    - - 128
      - 1
      - 1
    - - 256
      - 3
      - 1
    - - S
