dataset:
  root_dir: /home/aldo/opt/dataset/Anti-UAV-RGBT
  train_loader_path: data/train_dataloader.pickle
  val_loader_path: data/val_dataloader.pickle
  test_loader_path: data/test_dataloader.pickle
  batch_size: 4
  remote: false
  image_size:
  - 640
  - 640
  workers: 16
  mosaic: false
  format: yolo

train:
  seed: 211
  model: yolov3
  hparams:
    anchors:
    - - - 29
        - 23
      - - 48
        - 30
      - - 67
        - 38
    - - - 91
        - 54
      - - 120
        - 75
      - - 157
        - 60
    - - - 199
        - 73
      - - 315
        - 92
      - - 268
        - 182
    head_scales:           # x0, x1, x2
    - 32
    - 16
    - 8
    lr: 0.0001
    lr_scheduler: false
    attention_temperature: 30
    optim:
        name: SGD
        momentum: 0.7
    num_dy_conv:
    - 3
    - 3
    - 3
    dy_kernel_size:
    - 3
    - 3
    - 3
    loss_balancing:
      obj_scales_w:
      - 2.0
      - 1.0
      - 0.5
      bbox_w: 4.0
      objectness_w: 1.0
      no_obj_w: 4.0
  trainer:
    epochs: 5
    input_size:
    - 3
    - 640
    - 640
    profiler: null
    grad_batches: 2
    train_batches: 1.0
    val_batches: 1.0
    val_check_interval: 1.0
    accelerator: gpu
    devices: 1
    precision: 16
    grad_clip_val: null
  checkpoint:
    dir: logs/checkpoints
    monitor: val_loss
    mode: min
