dataset:
  root_dir: /home/aldo/opt/dataset/Anti-UAV-RGBT
  train_loader_path: data/train_dataloader.pickle
  val_loader_path: data/val_dataloader.pickle
  train_batch_size: 8
  val_batch_size: 8
  remote: false
  image_size: [640, 640]
  workers: 16
  mosaic: false

train:
  seed: 11
  model: proposed
  hparams:
    anchors: [
      [[29, 23], [48, 30], [67, 38]], # x0: small scale
      [[91, 54], [120, 75], [157, 60]], # x1: medium scale
      [[199, 73], [315, 92], [268, 182]] # x2: large scale
    ] 
    head_scales: [2, 4, 8] # x0, x1, x2
    lr: 0.001
    attention_temperature: 30
    optim: Adam
    num_dy_conv: [3, 3, 3]
    dy_kernel_size: [3, 3, 3]
    loss_balancing:
      obj_scales_w: [2.0, 1.0, 0.5]
      bbox_w: 4.0
      objectness_w: 1.0
  trainer:
    epochs: 2
    input_size: [3, 640, 640]
    profiler: null
    grad_batches: 4
    train_batches: 1.0
    val_batches: 0.25  
    val_check_interval: 4000
    accelerator: gpu
    devices: 1
    precision: high
  checkpoint:
    dir: logs/checkpoints
    monitor: val_loss
    mode: min