hydra:
  output_subdir: null  
  run:
    dir: .

defaults:
  - _self_
  - model: dy_yolo

dataset:
  root_dir: /home/aldo/opt/dataset/Anti-UAV-RGBT
  train_loader_path: data/train_dataloader.pickle
  val_loader_path: data/val_dataloader.pickle
  test_loader_path: data/test_dataloader.pickle
  batch_size: 4
  remote: false
  image_size: [416, 416]
  workers: 32
  mosaic: false
  format: yolo

train:
  seed: 211
  trainer:
    epochs: 5
    input_size: [3, 416, 416]
    profiler: null
    grad_batches: 2
    train_batches: 1.0
    val_batches: 1.0
    val_check_interval: 1.0
    accelerator: gpu
    devices: 1
    precision: 32
    grad_clip_val: null
  checkpoint:
    dir: logs/checkpoints
    monitor: val_loss
    mode: min
