defaults:
  - _self_
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none

hydra:
  output_subdir: null  
  run:
    dir: .

dataset:
  root_dir: /home/aldo/opt/dataset/Anti-UAV-RGBT
  train_batch_size: 8
  val_batch_size: 8
  remote: false
  image_size: [640, 640]
  workers: 2
  mosaic: false

train:
  model: proposed
  hparams:
    anchors: [
      [[29, 23], [48, 30], [67, 38]], # x0: small scale
      [[91, 54], [120, 75], [157, 60]], # x1: medium scale
      [[199, 73], [315, 92], [268, 182]] # x2: large scale
    ] 
    head_scales: [2, 4, 8] # x0, x1, x2
    lr: 0.001
    attention_temperature: 20
    optim: Adam
    num_dy_conv: 3
    dy_kernel_size: 3
  trainer:
    epochs: 4
    input_size: [3, 640, 640]
    profiler: null
    grad_batches: 4
    train_batches: 1.0
    val_batches: 1.0
    accelerator: gpu
    devices: 1
    seed: 11
    precision: high



