defaults:
  - _self_
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none

hydra:
  output_subdir: null  
  run:
    dir: .

dataset:
  root_dir: /home/aldo/opt/dataset/Anti-UAV-RGBT
  train_batch_size: 1
  val_batch_size: 4
  remote: false
  image_size: [640, 640]
  workers: 8
  mosaic: true

train:
  model: RTMUAVDet
  hparams:
    anchors: [
      [[12, 16], [19, 36], [40, 28]], # x1: small scale
      [[30, 61], [62, 45], [59, 119]] # x2: medium scale
    ] 
    det_scales: [160, 80]
    lr: 0.0001
    optim: SGD
  trainer:
    epochs: 1
    input_size: [3, 640, 640]
    profiler: null
    grad_batches: 4
    train_batches: 0.1
    val_batches: 0.1
    accelerator: gpu
    devices: 1
    seed: 11
    precision: high



