name: baseline
hparams:
  anchors: [
    [[29, 23], [48, 30], [67, 38]],
    [[91, 54], [120, 75], [157, 60]],
    [[199, 73], [315, 92], [268, 182]]
  ]
  head_scales: [32, 16, 8] # x0, x1, x2
  lr: 0.0001
  lr_scheduler: false
  loss_balancing:
    obj_scales_w: [2.0, 1.0, 0.5]
    bbox_w: 4.0
    objectness_w: 1.0
    no_obj_w: 4.0
  bbox_loss_fn: 'mse'
  optim:
    name: SGD
    momentum: 0.7
  layer_config: [
    [32, 3, 1],
    [64, 3, 2],
    ["B", 1],
    [128, 3, 2],
    ["B", 2],
    [256, 3, 2],
    ["B", 8],
    [512, 3, 2],
    ["B", 8], 
    [1024, 3, 2],
    ["B", 4],
    # DarkNet-53
    [512, 1, 1],
    [1024, 3, 1],
    ["S"],
    [256, 1, 1],
    ["U"],
    [256, 1, 1],
    [512, 3, 1],
    ["S"],
    [128, 1, 1],
    ["U"],
    [128, 1, 1],
    [256, 3, 1],
    ["S"],
]

